### ISSUE TITLE
Reverse order of API Version Reports

### ISSUE THREAD

**Issue by DenisCarriere** [EOS-Nation/bpvalidate#42] opened 2019-04-28 17:19 UTC
Sort by most recent release to oldest release:
- 1.7.3 (most recent) first items
- 1.4.4 (oldest) last items

https://validate.eosnation.io/mainnet/reports/api_versions.html

![image](https://user-images.githubusercontent.com/550895/56867823-45f39100-69b8-11e9-95b6-4d928867384e.png)

**Comment by matthewdarwin** [comment] 2019-04-28 17:24
Duplicate of https://github.com/EOS-Nation/bpvalidate/issues/40

**Closed by matthewdarwin** 2019-04-28 17:24 UTC
